### PR TITLE
Remove bad entry

### PR DESCRIPTION
**Pull request by erdembayar**

### CODE REVIEW

**Review by nkolev92 — COMMENTED** [review]
Can you run the builds on the test branches directly? 

I don't think you need to create PR for every little improvement. 
Might make your inner loop faste.r

**Comment by erdembayar** [comment]
> Can you run the builds on the test branches directly?
> 
> I don't think you need to create PR for every little improvement. Might make your inner loop faste.r

Yes, I tried it. Somehow [after waiting 2 hours](https://dev.azure.com/dnceng/internal/_build/results?buildId=1691135&view=logs&j=a3dd7907-8eb7-56c3-5e5e-d779decc673d) it just timed out without executing anything.

**Comment by nkolev92** [comment]
If you click on the pipeline, you'll see that the yml is broken and it's breaking the triggers.

Maybe merge this and the next one for a separate branch works.

**Comment by nkolev92** [comment]
Basically it has `Some recent issues detected related to pipeline trigger.`

**Review by nkolev92 — APPROVED** [review]

**Pull request merged**
